[versions]
agp = "8.9.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
ssp = "1.1.1"
sdp = "1.1.1"
splashscreen = "1.0.1"

room-version = "2.8.3"
daggerHilt = "2.57.2"
ksp = "2.0.21-1.0.27"
activity-ktx = "1.12.2"

firebaseGms = "4.4.3"
firebaseCrashlytics = "2.9.2"
firebasePerf = "1.4.2"
coreCrocodic = "4.0.11"

biometric = "1.4.0-alpha02"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
ssp = { group = "com.intuit.ssp", name = "ssp-android", version.ref = "ssp" }
sdp = { group = "com.intuit.sdp", name = "sdp-android", version.ref = "sdp" }
splashscreen = { group = "androidx.core", name = "core-splashscreen",  version.ref = "splashscreen"}

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room-version" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-version" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room-version" }
daggerHilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
daggerHiltCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "daggerHilt" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }
coreCrocodic = { group = "com.github.crocodic-studio", name = "AndroidCoreProject", version.ref = "coreCrocodic" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

daggerHilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

firebaseGms = { id = "com.google.gms.google-services", version.ref = "firebaseGms" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebasePerf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }